- name: play1
  hosts: all
  tasks:
    - name: Print the gateway for each host when defined
        ansible.builtin.debug:
          msg: System
- name: Update web servers
  hosts: all
  remote_user: root

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest