- name: Ansible Variables
  hosts: all
  vars:
    URL: google.com
    ORGS:
      - Google
      - Apple
      - Meta
    vars_prompt:
      - name: URL
        prompt
  tasks:
    - name: task1 - printing global variables
      ansible.builtin.debug:
        msg: variable value is {{ URL }}
    - name: task - printing local variables
      ansible.builtin.debug:
        msg: global variable value is {{ URL }} and local variable value is {{ URL_LOCAL }}
      vars:
        URL_LOCAL: local.google.com
        URL: task.google.com
    - name: task - printing undeclared or cli variables
      ansible.builtin.debug:
        msg: variable value is {{ ORGS }}