- name: Ansible Variables
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: task1 - printing gvariables
      ansible.builtin.debug:
        msg: variable value is {{ URL }}
    - name: task - printing variables
      ansible.builtin.debug:
        msg: variable value is {{ URL }}
      vars:
        URL: local.google.com
    - name: task - printing variables
      ansible.builtin.debug:
        msg: variable value is {{ URL }}