- name: Ansible Variables
  hosts: all
  vars:
    URL: google.com
  task:
    - name: printing variables
      ansible.buildin.debug:
        msg: variable value is {{ URL }}
    - name: printing variables
      ansible.buildin.debug:
        msg: variable value is {{ URL }}
      vars:
      