- name: Demo Facts
  hosts: all
  tasks:
  - name: prining facts
    ansible.builtin.debug:
      msg: "{{ ansible_distribution }}"
  - name: prining 
    ansible.builtin.debug:
      msg: "{{ ansible_dns }}"
