- name: Demo Facts
  hosts: all
  tasks:
  - name: prining Distro
    ansible.builtin.debug:
      msg: "{{ ansible_distribution }}"
  - name: prining IP address
    ansible.builtin.debug:
      msg: "{{  }}"
