- name: Handling Errors
  hosts: all
  tasks:
  - name: Check if tomcat is running or not
    shell: ps -ef | grep java | grep 
    register: OUT
  - name: Printing output of uptime
    debug:
      msg: "{{ OUT.stdout }}"